Repository kerala-blockchain-academy/ethereum-developer-program, pull requests merged in 2025-03, with the labels that each got.

#6 ♻️ | refactor dapp-client-side with ts
  dapp-client-side/.eslintrc.cjs
  dapp-client-side/eslint.config.js
  dapp-client-side/index.html
  dapp-client-side/package.json
  dapp-client-side/src/App.css
  dapp-client-side/src/App.tsx
  dapp-client-side/src/deployed_addresses.json
  dapp-client-side/src/index.css
  dapp-client-side/src/main.jsx
  dapp-client-side/src/main.tsx
  dapp-client-side/src/vite-env.d.ts
  dapp-client-side/tsconfig.app.json
  dapp-client-side/tsconfig.json
  dapp-client-side/tsconfig.node.json
  dapp-client-side/vite.config.ts
Labels: enhancement

#10 📝 | update main readme
  README.md
  assets/images/Docs.png
  assets/images/GitHub.png
  assets/images/Telegram.png
  assets/images/Videos.png
Labels: documentation

#12 🔨 | add Bash script containing CURL requests without dynamic params
  json-rpc/curl_request.sh
Labels: enhancement, sh
